### PR TITLE
Fix Flag

### LINKED ISSUE #40: flogo commands ends in error
After taking the latest cli [@8cf8b43](https://github.com/project-flogo/cli/tree/8cf8b43d97113753521feff53b0db81756867b31) using `go get -u github.com/project-flogo/cli/...`, I get the following error for any flogo command I use:

```bash
C:\Users\apandura\Desktop\AnandDocuments\workspace\web-ui>flogo
panic: "cv" shorthand is more than one ASCII character

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0000da300, 0xc000053220)
        C:/Users/apandura/Desktop/AnandDocuments/goworkspace-test/src/github.com/spf13/pflag/flag.go:852 +0x77d
github.com/spf13/pflag.(*FlagSet).VarPF(0xc0000da300, 0x8e4700, 0xba5ba0, 0x86e6cd, 0xb, 0x86c206, 0x2, 0x876873, 0x1c, 0xc000053180)
        C:/Users/apandura/Desktop/AnandDocuments/goworkspace-test/src/github.com/spf13/pflag/flag.go:819 +0x112
github.com/spf13/pflag.(*FlagSet).VarP(0xc0000da300, 0x8e4700, 0xba5ba0, 0x86e6cd, 0xb, 0x86c206, 0x2, 0x876873, 0x1c)
        C:/Users/apandura/Desktop/AnandDocuments/goworkspace-test/src/github.com/spf13/pflag/flag.go:825 +0x95
github.com/spf13/pflag.(*FlagSet).StringVarP(0xc0000da300, 0xba5ba0, 0x86e6cd, 0xb, 0x86c206, 0x2, 0x0, 0x0, 0x876873, 0x1c)
        C:/Users/apandura/Desktop/AnandDocuments/goworkspace-test/src/github.com/spf13/pflag/string.go:42 +0xb1
github.com/project-flogo/cli/commands.init.1()
        C:/Users/apandura/Desktop/AnandDocuments/goworkspace-test/src/github.com/project-flogo/cli/commands/create.go:45 +0x10a
```

### PR DESCRIPTION
**Pull request by skothari-tibco**
Fixes #40

### CODE REVIEW

File: commands/create.go [hunk 1]
```diff
@@ -42,6 +42,6 @@ var CreateCmd = &cobra.Command{
 
 func init() {
 	CreateCmd.Flags().StringVarP(&flogoJsonPath, "file", "f", "", "path to flogo.json file")
-	CreateCmd.Flags().StringVarP(&coreVersion, "coreVersion", "cv", "", "specify core library version")
+	CreateCmd.Flags().StringVarP(&coreVersion, "coreVersion", "c", "", "specify core library version")
```
Comment (fm-tibco) [inline commands/create.go]: I think if we use `CreateCmd.Flags().StringVarP(&coreVersion, "cv", "", "", "specify core library version")`
would probably be better.  People will have to use --cv instead of -c,  and i think -coreVersion is overkill anyways.

File: commands/install.go [hunk 2]
```diff
@@ -44,7 +44,7 @@ var installCmd = &cobra.Command{
 
 func init() {
 	installCmd.Flags().StringVarP(&localContrib, "localContrib", "l", "", "Specify local Contrib")
-	installCmd.Flags().StringVarP(&contribBundle, "contribBundle", "cb", "", "Specify ContribBundle")
+	installCmd.Flags().StringVarP(&contribBundle, "contribBundle", "c", "", "Specify ContribBundle")
```
Comment (fm-tibco) [inline commands/install.go]: -c isn't great.  would switch it to --cb `installCmd.Flags().StringVarP(&contribBundle, "cb", "", "", "specify a contribution bundle")`

Or maybe we should just get rid of this entirely.  We should just check if the value provided is file, and if it is, assume its a contribution bundle.  If we do this, we should probably also support http://, https://, file:// for accessing the file.   If it starts with one of these you can automatically assume its a contrib bundle.

Comment (skothari-tibco) [reply commands/install.go]: If we remove that, we will have to check if it's a contrib bundle file , a flogo contrib etc for every `flogo install` command. Would that be ok?

Comment (fm-tibco) [reply commands/install.go]: This can be done quickly if you check if it starts with file:,http:,https:,  ‘/‘, ‘.’.  But let’s not get fancy and just go with —cb for now

Comment (fm-tibco) [reply commands/install.go]: Annoying that you can’t use 2 characters for the short form!

Comment (fm-tibco) [reply commands/install.go]: We could just use -f ti specify a file

Comment (skothari-tibco) [reply commands/install.go]: @fm-tibco . Yup, I never thought they won't allow 2 characters for short form. And I never tested it.
