### PR TITLE
Duplicate fix

### LINKED ISSUE #47: The CLI output should indicate what version of core is being installed if specified with `--cv`
When using `--cv` to indicate a specific version of core, the CLI should display what version is being installed to avoid any confusion.

```
flogo create --cv master -f myapp.json
Creating Flogo App: MyApp
installing core
```

### PR DESCRIPTION
**Pull request by skothari-tibco**
Fixes #47 #48.

### CODE REVIEW

**Comment by skothari-tibco** [comment]
@debovema .

File: api/project.go [hunk 1]
```diff
@@ -158,17 +158,30 @@ func (p *appProjectImpl) addImportsInJson(ignoreError bool, imports ...util.Impo
 	json.Unmarshal([]byte(appDescriptorData), &appDescriptor)
 
 	// list existing imports in JSON to avoid duplicates
-	existingImports := make(map[string]bool)
+	existingImports := make(map[string]string)
 	jsonImports, _ := util.ParseImports(appDescriptor.Imports)
 	for _, e := range jsonImports {
-		existingImports[e.CanonicalImport()] = true
+		existingImports[e.ModulePath()] = e.CanonicalImport()
```
Comment (debovema) [inline api/project.go]: ```e.ModulePath()``` should not be used a key since it will break the alternate syntax and it does not select a unique contrib (the one being updated).
Based on @mellistibco request in #48, we should use method GoImportPath() of ```util.Import``` interface instead since it's the one used to add imports in *imports.go* file and we don't have duplicate in this one, do we?

```suggestion
		existingImports[e.GoImportPath()] = e
```

File: api/project.go [hunk 2]
```diff
@@ -158,17 +158,30 @@ func (p *appProjectImpl) addImportsInJson(ignoreError bool, imports ...util.Impo
...
-		if _, ok := existingImports[i.CanonicalImport()]; !ok {
-			appDescriptor.Imports = append(appDescriptor.Imports, i.CanonicalImport())
+		val, ok := existingImports[i.ModulePath()]
+		if !ok {
+			//appDescriptor.Imports = append(appDescriptor.Imports, i.CanonicalImport())
+			existingImports[i.ModulePath()] = i.CanonicalImport()
+		} else {
+			if i.CanonicalImport() != val {
+				delete(existingImports, val)
+				existingImports[i.ModulePath()] = i.CanonicalImport()
```
Comment (debovema) [inline api/project.go]: If there is an alias in the existing import we should keep it not to break the ```"ref": "#alias"``` references in other parts of *flogo.json*.

```suggestion
				alias := i.Alias()
				if val.Alias() != "" && i.Alias() == "" {
					alias = val.Alias()
				}
				existingImports[i.GoImportPath()] = util.NewFlogoImport(i.ModulePath(), i.RelativeImportPath(), i.Version(), alias)
```

File: api/project.go [hunk 3]
```diff
@@ -158,17 +158,30 @@ func (p *appProjectImpl) addImportsInJson(ignoreError bool, imports ...util.Impo
 	json.Unmarshal([]byte(appDescriptorData), &appDescriptor)
 
 	// list existing imports in JSON to avoid duplicates
-	existingImports := make(map[string]bool)
+	existingImports := make(map[string]string)
```
Comment (debovema) [inline api/project.go]:
```suggestion
	existingImports := make(map[string]util.Import)
```

File: api/project.go [hunk 4]
```diff
@@ -158,17 +158,30 @@ func (p *appProjectImpl) addImportsInJson(ignoreError bool, imports ...util.Impo
...
+		existingImports[e.ModulePath()] = e.CanonicalImport()
 	}
 
 	for _, i := range imports {
-		if _, ok := existingImports[i.CanonicalImport()]; !ok {
-			appDescriptor.Imports = append(appDescriptor.Imports, i.CanonicalImport())
+		val, ok := existingImports[i.ModulePath()]
+		if !ok {
+			//appDescriptor.Imports = append(appDescriptor.Imports, i.CanonicalImport())
+			existingImports[i.ModulePath()] = i.CanonicalImport()
```
Comment (debovema) [inline api/project.go]:
```suggestion
			existingImports[i.GoImportPath()] = i
```

File: api/project.go [hunk 5]
```diff
@@ -158,17 +158,30 @@ func (p *appProjectImpl) addImportsInJson(ignoreError bool, imports ...util.Impo
...
+		} else {
+			if i.CanonicalImport() != val {
```
Comment (debovema) [inline api/project.go]:
```suggestion
			if i.CanonicalImport() != val.CanonicalImport() {
```

File: api/project.go [hunk 6]
```diff
@@ -158,17 +158,30 @@ func (p *appProjectImpl) addImportsInJson(ignoreError bool, imports ...util.Impo
...
+				delete(existingImports, val)
```
Comment (debovema) [inline api/project.go]:
```suggestion
				delete(existingImports, val.GoImportPath())
```

File: go.mod [hunk 7]
```diff
@@ -3,6 +3,7 @@ module github.com/project-flogo/cli
 require (
 	github.com/msoap/byline v1.1.1
 	github.com/project-flogo/core v0.9.0-alpha.6
+	github.com/sirupsen/logrus v1.4.0
```
Comment (fm-tibco) [inline go.mod]: Why is this required

Comment (skothari-tibco) [reply go.mod]: It's not but sometimes doing a go build adds logrus. It's inconsistent. We can remove it

**Comment by fm-tibco** [comment]
@debovema how does this look? Is it ready to merge in your opinion?

**Comment by fm-tibco** [comment]
I'm going to merge this, if needed we can create another PR to resolve any outstanding issues.
